import { getReaderBookDetail, type ReaderBookDetail } from "@/src/lib/readerBookDetails";

export type ExploreOption = "english" | "khmer";

export type ExploreCategoryCollection = {
  id: string;
  title: string;
  englishTitle: string; // used for DB queries - always the English name
  subtitle: string;
  color: string;
  heroBookId: string;
  heroImage: string;
  backgroundImages: string[];
  bookIds: string[];
};

const sharedBackgroundBooks = [
  "/MainPage/Books/Are you my mother.jpg",
  "/MainPage/Books/Atomic_habits.jpg",
  "/MainPage/Books/Germany Travel Book.jpg",
  "/MainPage/Books/The I Hate To Cook Book.jpg",
];

const khmerBookImages = [
  "/MainPage/Books/khmer_Books/image.png",
  "/MainPage/Books/khmer_Books/image copy.png",
  "/MainPage/Books/khmer_Books/image copy 2.png",
  "/MainPage/Books/khmer_Books/image copy 3.png",
  "/MainPage/Books/khmer_Books/image copy 4.png",
  "/MainPage/Books/khmer_Books/image copy 5.png",
];

const khmerBackgroundBooks = khmerBookImages.slice(0, 4);

export const englishExploreCategories: ExploreCategoryCollection[] = [
  {
    id: "self-help",
    title: "Self-Help",
    englishTitle: "Self-Help",
    subtitle: "Popular self-growth and practical books for readers who want to improve day by day.",
    color: "from-[#6e8465] to-[#49604a]",
    heroBookId: "atomic-habits",
    heroImage: "/MainPage/Books/Atomic_habits.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["atomic-habits", "life-impossible", "verity", "favorites", "three-days-in-june"],
  },
  {
    id: "fantasy",
    title: "Fantasy",
    englishTitle: "Fantasy",
    subtitle: "Magical worlds, adventure, mystery, and beautiful escapist fiction.",
    color: "from-[#d85f58] to-[#9f3e3a]",
    heroBookId: "castle-in-the-moon",
    heroImage: "/MainPage/Books/The Castle In the Moon.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["castle-in-the-moon", "castle-in-the-mist", "thorns-and-roses", "wild-dark-shore", "song-of-achilles"],
  },
  {
    id: "historical",
    title: "Historical",
    englishTitle: "Historical",
    subtitle: "Stories with rich atmosphere, memory, and time-shaped settings.",
    color: "from-[#5faa39] to-[#467d28]",
    heroBookId: "castle-in-the-mist",
    heroImage: "/MainPage/Books/The Castle In the Mist.jpeg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["castle-in-the-mist", "song-of-achilles", "three-days-in-june", "dirt", "favorites"],
  },
  {
    id: "sci-fi",
    title: "Sci-Fi",
    englishTitle: "Sci-Fi",
    subtitle: "Futuristic, imaginative, and emotionally immersive speculative reads.",
    color: "from-[#1d2bca] to-[#10196f]",
    heroBookId: "life-impossible",
    heroImage: "/MainPage/Books/9780399547003.jpeg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["life-impossible", "wild-dark-shore", "castle-in-the-mist", "favorites", "listen-for-the-lie"],
  },
  {
    id: "classics",
    title: "Classics",
    englishTitle: "Classics",
    subtitle: "Recognizable titles and timeless stories that still feel fresh.",
    color: "from-[#cb7a73] to-[#954f4a]",
    heroBookId: "lessons-in-chemistry",
    heroImage: "/MainPage/Books/12132023_Book_Cover-Lessons_in_Chemistry_152020.jpg.webp",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["are-you-my-mother", "lessons-in-chemistry", "three-days-in-june", "song-of-achilles", "verity"],
  },
  {
    id: "science",
    title: "Science",
    englishTitle: "Science",
    subtitle: "Books for curious minds who enjoy ideas, knowledge, and discovery.",
    color: "from-[#db5bc8] to-[#983992]",
    heroBookId: "all-the-single-ladies",
    heroImage: "/MainPage/Books/9780062390769_p0_v4_s600x595.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["lessons-in-chemistry", "all-the-single-ladies", "atomic-habits", "life-impossible", "favorites"],
  },
  {
    id: "finance",
    title: "Finance",
    englishTitle: "Finance",
    subtitle: "Smart money and practical thinking for readers who want useful insight.",
    color: "from-[#d5ad56] to-[#9a7331]",
    heroBookId: "atomic-habits",
    heroImage: "/MainPage/Books/Atomic_habits.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["atomic-habits", "life-impossible", "all-the-single-ladies", "favorites", "verity"],
  },
  {
    id: "mystery",
    title: "Mystery",
    englishTitle: "Mystery",
    subtitle: "Suspenseful, twisty books that keep readers curious until the end.",
    color: "from-[#6954f0] to-[#4532aa]",
    heroBookId: "listen-for-the-lie",
    heroImage: "/MainPage/Books/listen-for-the-lie.jpeg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["listen-for-the-lie", "verity", "wild-dark-shore", "favorites", "castle-in-the-mist"],
  },
  {
    id: "philosophy",
    title: "Philosophy",
    englishTitle: "Philosophy",
    subtitle: "Reflective, idea-driven reads for slow thoughtful reading.",
    color: "from-[#cb3b2e] to-[#8d1f18]",
    heroBookId: "are-you-my-mother",
    heroImage: "/MainPage/Books/Are you my mother.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["atomic-habits", "life-impossible", "elf-shack", "three-days-in-june", "song-of-achilles"],
  },
  {
    id: "biography",
    title: "Biography",
    englishTitle: "Biography",
    subtitle: "Personal stories, life journeys, and books with a human center.",
    color: "from-[#b2be4d] to-[#76812e]",
    heroBookId: "all-the-single-ladies",
    heroImage: "/MainPage/Books/all-the-single-ladies.jpg.webp",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["all-the-single-ladies", "favorites", "dirt", "three-days-in-june", "life-impossible"],
  },
  {
    id: "romance",
    title: "Romance",
    englishTitle: "Romance",
    subtitle: "Warm, emotional, and relationship-driven books for comfort reading.",
    color: "from-[#d9d9db] to-[#aeb3b9]",
    heroBookId: "it-ends-with-us",
    heroImage: "/MainPage/Books/12132023_Book_Cover-Lessons_in_Chemistry_152020.jpg.webp",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["it-ends-with-us", "thorns-and-roses", "all-the-single-ladies", "favorites", "three-days-in-june"],
  },
  {
    id: "travel",
    title: "Travel",
    englishTitle: "Travel",
    subtitle: "Place-based books and destination-inspired reading for wanderers.",
    color: "from-[#402420] to-[#241311]",
    heroBookId: "germany-travel-book",
    heroImage: "/MainPage/Books/Germany Travel Book.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["germany-travel-book", "life-impossible", "dirt", "favorites", "three-days-in-june"],
  },
  {
    id: "drama",
    title: "Drama",
    englishTitle: "Drama",
    subtitle: "Emotion-rich stories with tension, relationships, and strong character arcs.",
    color: "from-[#5dcf69] to-[#359048]",
    heroBookId: "favorites",
    heroImage: "/MainPage/Books/the-favorites.jpeg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["favorites", "it-ends-with-us", "thorns-and-roses", "dirt", "life-impossible"],
  },
  {
    id: "cooking",
    title: "Cooking",
    englishTitle: "Cooking",
    subtitle: "Practical and casual cooking books for readers who want something useful.",
    color: "from-[#6cf0ca] to-[#3cb98e]",
    heroBookId: "hate-to-cook-book",
    heroImage: "/MainPage/Books/The I Hate To Cook Book.jpg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["hate-to-cook-book", "atomic-habits", "germany-travel-book", "all-the-single-ladies", "life-impossible"],
  },
  {
    id: "horror",
    title: "Horror",
    englishTitle: "Horror",
    subtitle: "Dark, eerie, and atmospheric reads with a stronger edge.",
    color: "from-[#334e73] to-[#223754]",
    heroBookId: "wild-dark-shore",
    heroImage: "/MainPage/Books/The Castle In the Mist.jpeg",
    backgroundImages: sharedBackgroundBooks,
    bookIds: ["wild-dark-shore", "listen-for-the-lie", "castle-in-the-mist", "verity", "favorites"],
  },
];

export const khmerExploreCategories: ExploreCategoryCollection[] = [
  {
    id: "self-help",
    title: "ជំនួយខ្លួនឯង",
    englishTitle: "Self-Help",
    subtitle: "សៀវភៅខ្មែរដែលជួយអភិវឌ្ឍខ្លួនឯង និងជីវិតប្រចាំថ្ងៃ។",
    color: "from-[#6e8465] to-[#49604a]",
    heroBookId: "khmer-1",
    heroImage: khmerBookImages[0],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-1", "khmer-6", "khmer-5", "khmer-2"],
  },
  {
    id: "fantasy",
    title: "រឿងអស្ចារ្យ",
    englishTitle: "Fantasy",
    subtitle: "ពិភពមន្តអាគម និងការ冒险នៅក្នុងអក្សរសិល្ប៍ខ្មែរ។",
    color: "from-[#d85f58] to-[#9f3e3a]",
    heroBookId: "khmer-2",
    heroImage: khmerBookImages[1],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-2", "khmer-3", "khmer-1", "khmer-4"],
  },
  {
    id: "historical",
    title: "ប្រវត្តិសាស្ត្រ",
    englishTitle: "Historical",
    subtitle: "សៀវភៅខ្មែរដែលពិពណ៌នាអំពីប្រវត្តិ និងវប្បធម៌។",
    color: "from-[#5faa39] to-[#467d28]",
    heroBookId: "khmer-3",
    heroImage: khmerBookImages[2],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-3", "khmer-4", "khmer-1", "khmer-5"],
  },
  {
    id: "sci-fi",
    title: "វិទ្យាសាស្ត្រប្រឌិត",
    englishTitle: "Sci-Fi",
    subtitle: "រឿងប្រឌិតផ្អែកលើវិទ្យាសាស្ត្រ និងបច្ចេកវិទ្យា។",
    color: "from-[#1d2bca] to-[#10196f]",
    heroBookId: "khmer-4",
    heroImage: khmerBookImages[3],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-4", "khmer-2", "khmer-3", "khmer-5"],
  },
  {
    id: "classics",
    title: "អក្សរសិល្ប៍ក្លាស្សិក",
    englishTitle: "Classics",
    subtitle: "សៀវភៅខ្មែរបុរាណដ៏ល្បីល្បាញ។",
    color: "from-[#cb7a73] to-[#954f4a]",
    heroBookId: "khmer-5",
    heroImage: khmerBookImages[4],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-5", "khmer-1", "khmer-2", "khmer-4"],
  },
  {
    id: "science",
    title: "វិទ្យាសាស្ត្រ",
    englishTitle: "Science",
    subtitle: "សៀវភៅចំណេះដឹងវិទ្យាសាស្ត្រ សម្រាប់អ្នកចូលចិត្តស្រាវជ្រាវ។",
    color: "from-[#db5bc8] to-[#983992]",
    heroBookId: "khmer-6",
    heroImage: khmerBookImages[5],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-6", "khmer-1", "khmer-3", "khmer-5"],
  },
  {
    id: "finance",
    title: "ហិរញ្ញវត្ថុ",
    englishTitle: "Finance",
    subtitle: "ចំណេះដឹងហិរញ្ញវត្ថុ និងការគ្រប់គ្រងប្រាក់កាស។",
    color: "from-[#d5ad56] to-[#9a7331]",
    heroBookId: "khmer-1",
    heroImage: khmerBookImages[0],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-1", "khmer-6", "khmer-2", "khmer-3"],
  },
  {
    id: "mystery",
    title: "អាថ៌កំបាំង",
    englishTitle: "Mystery",
    subtitle: "រឿងដ៏គួរឱ្យចង់ដឹង និងអាថ៌កំបាំងសម្រាប់អ្នកអាន។",
    color: "from-[#6954f0] to-[#4532aa]",
    heroBookId: "khmer-2",
    heroImage: khmerBookImages[1],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-2", "khmer-4", "khmer-3", "khmer-5"],
  },
  {
    id: "philosophy",
    title: "ទស្សនវិជ្ជា",
    englishTitle: "Philosophy",
    subtitle: "ការគិតស៊ីជម្រៅ និងទស្សនវិជ្ជាខ្មែរ។",
    color: "from-[#cb3b2e] to-[#8d1f18]",
    heroBookId: "khmer-3",
    heroImage: khmerBookImages[2],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-3", "khmer-1", "khmer-6", "khmer-5"],
  },
  {
    id: "biography",
    title: "ជីវប្រវត្តិ",
    englishTitle: "Biography",
    subtitle: "រឿងជីវិតពិត និងបទពិសោធន៍របស់មនុស្សល្បី។",
    color: "from-[#b2be4d] to-[#76812e]",
    heroBookId: "khmer-4",
    heroImage: khmerBookImages[3],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-4", "khmer-2", "khmer-1", "khmer-3"],
  },
  {
    id: "romance",
    title: "រឿងស្នេហា",
    englishTitle: "Romance",
    subtitle: "រឿងស្នេហាខ្មែរ ដ៏ពណ៌ស្រស់ និងទន់ភ្លន់។",
    color: "from-[#d9d9db] to-[#aeb3b9]",
    heroBookId: "khmer-5",
    heroImage: khmerBookImages[4],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-5", "khmer-4", "khmer-2", "khmer-1"],
  },
  {
    id: "travel",
    title: "ទេសចរណ៍",
    englishTitle: "Travel",
    subtitle: "ការរៀបរាប់អំពីដំណើរទេសចរណ៍ និងកន្លែងគួរចូលទស្សនា។",
    color: "from-[#402420] to-[#241311]",
    heroBookId: "khmer-6",
    heroImage: khmerBookImages[5],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-6", "khmer-3", "khmer-2", "khmer-1"],
  },
  {
    id: "drama",
    title: "រឿងនាដកម្ម",
    englishTitle: "Drama",
    subtitle: "រឿងដ៏អារម្មណ៍ណ៍ ពោរពេញដោយបទពិសោធន៍ជីវិត។",
    color: "from-[#5dcf69] to-[#359048]",
    heroBookId: "khmer-1",
    heroImage: khmerBookImages[0],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-1", "khmer-4", "khmer-3", "khmer-2"],
  },
  {
    id: "cooking",
    title: "ធ្វើម្ហូប",
    englishTitle: "Cooking",
    subtitle: "ម្ហូបខ្មែរ និងការណែនាំធ្វើម្ហូបប្រចាំថ្ងៃ។",
    color: "from-[#6cf0ca] to-[#3cb98e]",
    heroBookId: "khmer-2",
    heroImage: khmerBookImages[1],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-2", "khmer-6", "khmer-1", "khmer-5"],
  },
  {
    id: "horror",
    title: "រឿងភ័យខ្លាច",
    englishTitle: "Horror",
    subtitle: "រឿងដ៏គួរឱ្យភ័យខ្លាច និងមានបរិយាកាសងងឹត។",
    color: "from-[#334e73] to-[#223754]",
    heroBookId: "khmer-3",
    heroImage: khmerBookImages[2],
    backgroundImages: khmerBackgroundBooks,
    bookIds: ["khmer-3", "khmer-4", "khmer-2", "khmer-5"],
  },
];

export function getExploreCategories(option: ExploreOption) {
  return option === "khmer" ? khmerExploreCategories : englishExploreCategories;
}

export function getExploreCategory(option: ExploreOption, categoryId: string) {
  return getExploreCategories(option).find((category) => category.id === categoryId);
}

export async function getExploreCategoryBooks(category: ExploreCategoryCollection): Promise<ReaderBookDetail[]> {
  const books = await Promise.all(
    category.bookIds.map((id) => getReaderBookDetail(id))
  );

  return books.filter((book): book is ReaderBookDetail => Boolean(book));
}
